
import { BibleBook } from './types';

export const BIBLE_BOOKS: BibleBook[] = [
    // Old Testament
    { name: '創世記', chapters: 50, testament: 'Old' },
    { name: '出埃及記', chapters: 40, testament: 'Old' },
    { name: '利未記', chapters: 27, testament: 'Old' },
    { name: '民數記', chapters: 36, testament: 'Old' },
    { name: '申命記', chapters: 34, testament: 'Old' },
    { name: '約書亞記', chapters: 24, testament: 'Old' },
    { name: '士師記', chapters: 21, testament: 'Old' },
    { name: '路得記', chapters: 4, testament: 'Old' },
    { name: '撒母耳記上', chapters: 31, testament: 'Old' },
    { name: '撒母耳記下', chapters: 24, testament: 'Old' },
    { name: '列王紀上', chapters: 22, testament: 'Old' },
    { name: '列王紀下', chapters: 25, testament: 'Old' },
    { name: '歷代志上', chapters: 29, testament: 'Old' },
    { name: '歷代志下', chapters: 36, testament: 'Old' },
    { name: '以斯拉記', chapters: 10, testament: 'Old' },
    { name: '尼希米記', chapters: 13, testament: 'Old' },
    { name: '以斯帖記', chapters: 10, testament: 'Old' },
    { name: '約伯記', chapters: 42, testament: 'Old' },
    { name: '詩篇', chapters: 150, testament: 'Old' },
    { name: '箴言', chapters: 31, testament: 'Old' },
    { name: '傳道書', chapters: 12, testament: 'Old' },
    { name: '雅歌', chapters: 8, testament: 'Old' },
    { name: '以賽亞書', chapters: 66, testament: 'Old' },
    { name: '耶利米書', chapters: 52, testament: 'Old' },
    { name: '耶利米哀歌', chapters: 5, testament: 'Old' },
    { name: '以西結書', chapters: 48, testament: 'Old' },
    { name: '但以理書', chapters: 12, testament: 'Old' },
    { name: '何西阿書', chapters: 14, testament: 'Old' },
    { name: '約珥書', chapters: 3, testament: 'Old' },
    { name: '阿摩司書', chapters: 9, testament: 'Old' },
    { name: '俄巴底亞書', chapters: 1, testament: 'Old' },
    { name: '約拿書', chapters: 4, testament: 'Old' },
    { name: '彌迦書', chapters: 7, testament: 'Old' },
    { name: '那鴻書', chapters: 3, testament: 'Old' },
    { name: '哈巴谷書', chapters: 3, testament: 'Old' },
    { name: '西番雅書', chapters: 3, testament: 'Old' },
    { name: '哈該書', chapters: 2, testament: 'Old' },
    { name: '撒迦利亞書', chapters: 14, testament: 'Old' },
    { name: '瑪拉基書', chapters: 4, testament: 'Old' },
    // New Testament
    { name: '馬太福音', chapters: 28, testament: 'New' },
    { name: '馬可福音', chapters: 16, testament: 'New' },
    { name: '路加福音', chapters: 24, testament: 'New' },
    { name: '約翰福音', chapters: 21, testament: 'New' },
    { name: '使徒行傳', chapters: 28, testament: 'New' },
    { name: '羅馬書', chapters: 16, testament: 'New' },
    { name: '哥林多前書', chapters: 16, testament: 'New' },
    { name: '哥林多後書', chapters: 13, testament: 'New' },
    { name: '加拉太書', chapters: 6, testament: 'New' },
    { name: '以弗所書', chapters: 6, testament: 'New' },
    { name: '腓立比書', chapters: 4, testament: 'New' },
    { name: '歌羅西書', chapters: 4, testament: 'New' },
    { name: '帖撒羅尼迦前書', chapters: 5, testament: 'New' },
    { name: '帖撒羅尼迦後書', chapters: 3, testament: 'New' },
    { name: '提摩太前書', chapters: 6, testament: 'New' },
    { name: '提摩太後書', chapters: 4, testament: 'New' },
    { name: '提多書', chapters: 3, testament: 'New' },
    { name: '腓利門書', chapters: 1, testament: 'New' },
    { name: '希伯來書', chapters: 13, testament: 'New' },
    { name: '雅各書', chapters: 5, testament: 'New' },
    { name: '彼得前書', chapters: 5, testament: 'New' },
    { name: '彼得後書', chapters: 3, testament: 'New' },
    { name: '約翰壹書', chapters: 5, testament: 'New' },
    { name: '約翰貳書', chapters: 1, testament: 'New' },
    { name: '約翰參書', chapters: 1, testament: 'New' },
    { name: '猶大書', chapters: 1, testament: 'New' },
    { name: '啟示錄', chapters: 22, testament: 'New' },
];
